ROR/eim/config/routes.rb
Eim::Application.routes.draw do  

  
  scope module: "demo" do
    root 'home_entries#index'

    match '/feeds', to: 'pages#home', via:'get'    
    

    match '/logout', to: 'home_entries#logout', via:'get'

    resources :sessions, only: [:new, :create, :destroy]
    match '/signin', to: 'sessions#new', via:'get'
    match '/signout', to: 'sessions#destroy', via:'delete'

    get 'search/user', to: 'search#search_user_hint'
    get 'search/group', to: 'search#search_group_hint'

    resources :users, only: [:create, :index, :edit, :update] do
      member do
        get :feeds
      end
      post :upload, on: :new, to: :upload_image
    end    

    match '/api/users/(:id)/info', to: 'users#info', via:'get'    

    resources :groups, only: [:index, :create, :update] do
      member do
        get :feeds
      end
      post :upload, on: :new, to: :upload_image
    end
    match '/api/groups/(:id)/info', to: 'groups#info', via:'get'
    match '/api/groups/(:id)/join', to: 'groups#join', via:'get'
    match '/api/groups/(:id)/leave', to: 'groups#leave', via:'get'
    match '/api/groups/(:id)/delete', to: 'groups#delete', via:'get'

    resources :conversations, only: [:show]
    match '/api/conversations/(:id)/info', to: 'conversations#info', via:'get'
    match '/api/conversations/(:id)/follow', to: 'conversations#follow', via:'get'
    match '/api/conversations/(:id)/unfollow', to: 'conversations#unfollow', via:'get'

    resources :posts, only: [:create, :update]
    match '/api/posts/(:id)/info', to: 'posts#info', via:'get'
    match '/api/posts/(:id)/like', to: 'posts#like', via:'get'
    match '/api/posts/(:id)/unlike', to: 'posts#unlike', via:'get'
    

    match '/api/users', to: 'api#users', via:'get'
    match '/api/groups', to: 'api#groups', via:'get'
    match '/api/networks', to: 'api#networks', via:'get'
    match '/api/feeds', to: 'api#feeds', via:'get'
    match '/api/unread_feeds_count', to: 'api#unread_feeds_count', via:'get'

    match '/api/searches/users', to: 'api#searches_users', via:'get'

    
  end

end

ROR/eim/app/views/shared/DEMO/frame/layout/_default_left_sidebar.html.erb
<% pin_unread_num = current_user.pinned_unread_feeds_count(current_network_id) %>

<div class="sidebar" data-type="default">
    <ul class="menu-sidebar">
        <li id="menu-sidebar-home-feeds">
            <a href="<%= feeds_path %>">
                <span class="icone icone-feed"></span>
                <%= t :feeds, scope: [:default_left_sidebar] %>
            </a>
        </li>        
        <li id="menu-sidebar-pinned-feeds">
            <a href="<%= pins_path %>">
                <span class="icone icone-pin"></span>
                <%= t :my_pinned, scope: [:default_left_sidebar] %>
            </a>
            <% if pin_unread_num > 0 %>
                <span class="count"><%= pin_unread_num %></span>
            <% end %>
        </li>
        <%= render 'shared/DEMO/frame/layout/left_sidebar_group_list' %>
        <li>
            <a href="http://www.linpus.com/">
                <span class="icone icone-help"></span>
                <%= t :help, scope: [:default_left_sidebar] %>
            </a>
        </li>
    </ul>

    <ul class="menu-sidebar">
        <%= render 'shared/DEMO/frame/layout/left_sidebar_network_list' %>
    </ul>

</div>

ROR/eim/app/views/shared/DEMO/frame/layout/_header.html.erb
<header>
	<div class="header">
		<section>
			<a class="logo" href="<%= root_path %>">
				<h1>Eim</h1>
				<img src="<%= asset_path 'DEMO/upload/logo.png' %>" />
			</a>			
			<div class="header-icons">
				<a href="javascript:void(0)" class="flag-icon" id="set-locale-btn"></a>
	      <a href="javascript:void(0)" id="notification-icon"><img src="<%= asset_path 'DEMO/img/notification-icon.png' %>"/><!-- <span class="notif-bubble">10</span> --></a>
	      <a href="<%= invites_path %>" id="invite-icon"><img src="<%= asset_path 'DEMO/img/invite-icon.png' %>"/></a>
	      <a href="http://www.linpus.com" id="login-button"><img src="<%= asset_path 'DEMO/img/info.png' %>"/></a>
	      <a href="<%= feeds_user_path(@current_user) %>" id="profile-link"><img src="<%= asset_path profile_photo_thumb(current_user) %>" title="<%= current_user.name %>"/></a>
      </div>
			<form id="search" accept-charset="UTF-8" action="/search" autocomplete="off" method="get">			
      	<input name="utf8" value="✓" type="hidden">
				<input type="text" name="search" placeholder="<%= t :search, scope: [:header] %>..." value="" />
				<input type="submit" value="search" />
			</form>			
			<div class="profile-menu-block">
				<ul id="profile-menu">
					<li><a href="<%= edit_user_path(@current_user) %>"><%= t :profile, scope: [:header] %></a>
					</li>
					<% if current_user.home_network_admin? %>
					<li><a href="<%= admin_path %>"><%= t :admin, scope: [:header] %></a>
					</li>
					<% end %>
					<li><a href="<%= settings_path %>"><%= t :settings, scope: [:header] %></a>
					</li>					
					<li class="last"><%= link_to t(:logout, scope: [:header]), signout_path, method: "delete" %>
					</li>
				</ul>
			</div>
		</section>
	</div>
	<div class="menu">
		<section>
			<ul id="main-menu">
				<li><a href="<%= feeds_path %>" class="active"><%= t :home, scope: [:header] %></a>
				</li>
				<li><a href="<%= groups_path %>"><%= t :groups, scope: [:header] %></a>
				</li>
				<li><a href="<%= tasks_path %>"><%= t :tasks, scope: [:header] %></a>
				</li>
				<li><a href="<%= events_path %>"><%= t :events, scope: [:header] %></a>
				</li>
				<li><a href="<%= files_path %>"><%= t :files, scope: [:header] %></a>
				</li>
				<li><a href="<%= users_path %>"><%= t :people, scope: [:header] %></a>
				</li>
				<% if current_user.home_network_admin? && params[:controller] == "admin/pages" %>
				<li><a href="<%= admin_path %>"><%= t :admin, scope: [:header] %></a>
				</li>
				<% end %>
			</ul>
		</section>
	</div>
</header>

ROR/eim/app/views/shared/DEMO/frame/layout/_left_sidebar_group_list.html.erb
<li class="open" id="menu-sidebar-mygroups">
	<a href="javascript:void(0)">
	    <span class="icone icone-group"></span><%= t :my_group, scope: [:default_left_sidebar] %>
	    <span class="arrow"></span>
	</a>
	<span class="count"></span>
	<ul id="group_list"></ul>
</li>

ROR/eim/app/views/shared/DEMO/frame/layout/_left_sidebar_network_list.html.erb
<li class="">
    <a href="javascript:void(0)">
        <span class="icone icone-network"></span><%= t :network, scope: [:default_left_sidebar] %>
        <span class="arrow"></span>
    </a>
    <ul id="network_list"></ul>
</li>

ROR/eim/app/views/shared/DEMO/frame/layout/_sessionless_footer.html.erb
<footer>
    <center>
        <p>© 2014 Eim Sales: 86-13761545598</p>
    </center>
</footer>

ROR/eim/app/views/shared/DEMO/frame/layout/_sessionless_header.html.erb
<header>
    <section>
        <a class="logo" href="<%= root_path %>">
            <h1>Eim</h1>
            <img src="<%= asset_path 'DEMO/img/logo-b.png' %>"/>
        </a>
        <ul id="main-menu">
            <li><a href="#">Learn More</a></li>
            <li><a href="#">Contact Sales</a></li>
            <li><a href="#">Pricing</a></li>
            <li><a href="<%= signin_path %>">Login</a></li>
            <li><a href="javascript:void(0)" id="set-locale-btn" style="border-left:1px solid #fff;padding-left:25px"></a></li>
        </ul>
    </section>
</header>

ROR/eim/app/views/shared/DEMO/frame/layout/_setting_left_sidebar.html.erb
<div class="sidebar">
    <ul class="menu-sidebar">
        <li><a href="<%= edit_user_path(current_user) %>"><span class="icone icone-profile"></span>Profile</a></li>
        <li><a href="<%= password_user_path(current_user) %>"><span class="icone icone-password"></span>Password</a></li>
        <li><a href="<%= settings_path %>"><span class="icone icone-setting"></span>Setting</a></li>
    </ul>
</div>